# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "9mREsvXDs9Gk89Ef"
    ports:
      - '3306:5432'